[package]
name = "thirdpass-rs"
version = "0.1.0"
authors = ["rndhouse <rndhouse@protonmail.com>"]
edition = "2018"
repository = "https://github.com/thirdpass-org/thirdpass-rs"
license = "MIT"
description = "Rust ecosystem extension for the Thirdpass package review system."

[lib]
name = "thirdpass_rs_lib"
path = "src/lib.rs"

[[bin]]
name = "thirdpass-rs"
path = "src/bin.rs"

[dependencies]
thirdpass-core = { path = "../../thirdpass/thirdpass-core", version = "0.3.1" }

anyhow = "1.0.31"
structopt = "0.3.14"
tempdir = "0.3.7"

url = "2.1.1"
reqwest = { version = "0.10.6", default-features = false, features = ["blocking", "rustls-tls"] }

serde = { version = "1.0.104", features = ["derive"] }
serde_json = "1.0.48"
